---
title: "Assignment 2: USGS Stream"
author: "Natasha Atkins"
format: pdf
editor: visual
---

## Week 3: Git and Stream Temperature

## Downloading the USGS Data

```{r}
#install.packages("dataRetrieval") 
library(dataRetrieval) 
library(tidyverse) 
library(here)  

#get usgs data 
siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)

#save data as a csv
write.csv(temp_data, here("Data", "usgs_stream_data_assn2.csv"), row.names = FALSE)
```

### Load data in instead – use after initial download from server

```{r}
temp_data_dwnld <- read.csv(here("Data","usgs_stream_data_assn2.csv"))
```

## Data processing

```{r}
# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")
# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)

# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()
```
